%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.6

-ifndef(erl_playground_pb).
-define(erl_playground_pb, true).

-define(erl_playground_pb_gpb_version, "3.26.6").

-ifndef('OPTIONS_LIST.SINGLE_OPTION_PB_H').
-define('OPTIONS_LIST.SINGLE_OPTION_PB_H', true).
-record('options_list.single_option',
        {key                    :: integer(),       % = 1, 32 bits
         value                  :: binary() | iolist() | undefined % = 2
        }).
-endif.

-ifndef('WEATHER_PB_H').
-define('WEATHER_PB_H', true).
-record(weather,
        {msg                    :: binary() | iolist() | undefined % = 1
        }).
-endif.

-ifndef('ECHO_PB_H').
-define('ECHO_PB_H', true).
-record(echo,
        {msg                    :: binary() | iolist() | undefined % = 1
        }).
-endif.

-ifndef('QUESTION_PB_H').
-define('QUESTION_PB_H', true).
-record(question,
        {msg                    :: binary() | iolist() | undefined % = 1
        }).
-endif.

-ifndef('MENU_CHOICE_PB_H').
-define('MENU_CHOICE_PB_H', true).
-record(menu_choice,
        {choice                 :: #'options_list.single_option'{} | undefined % = 1
        }).
-endif.

-ifndef('OPTIONS_LIST_PB_H').
-define('OPTIONS_LIST_PB_H', true).
-record(options_list,
        {options = []           :: [#'options_list.single_option'{}] % = 1
        }).
-endif.

-ifndef('SERVER_MESSAGE_PB_H').
-define('SERVER_MESSAGE_PB_H', true).
-record(server_message,
        {message                :: binary() | iolist() % = 1
        }).
-endif.

-ifndef('CREATE_SESSION_PB_H').
-define('CREATE_SESSION_PB_H', true).
-record(create_session,
        {username               :: binary() | iolist() % = 1
        }).
-endif.

-ifndef('REQ_PB_H').
-define('REQ_PB_H', true).
-record(req,
        {type                   :: 'create_session' | 'server_message' | 'options_list' | 'menu_choice' | 'weather' | 'question' | 'echo' | integer(), % = 1, enum req.type_enum
         create_session_data    :: #create_session{} | undefined, % = 2
         server_message_data    :: #server_message{} | undefined, % = 3
         options_list_data      :: #options_list{} | undefined, % = 4
         menu_choice_data       :: #menu_choice{} | undefined, % = 5
         weather_data           :: #weather{} | undefined, % = 6
         question_data          :: #question{} | undefined, % = 7
         echo_data              :: #echo{} | undefined % = 8
        }).
-endif.

-ifndef('ENVELOPE_PB_H').
-define('ENVELOPE_PB_H', true).
-record(envelope,
        {uncompressed_data      :: #req{}           % = 2
        }).
-endif.

-endif.
